<?php

namespace AppBundle\Repository;

/**
 * GamingConsoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamingConsoleRepository extends \Doctrine\ORM\EntityRepository
{
}
